### ISSUE TITLE
Ordering episodes in admin interface does not work

### ISSUE THREAD

**Issue by lottebelice** [michielhildebrand/tkk-demo#60]
When dragging/dropping episodes to re-order them on desktop and iPad, nothing happens.

**Comment by michielhildebrand** [comment]
I am not going to add that, because:

For TKK we are not going to use the admin interface at all. I have a script that generates all the files we need. Before the study we run this and hopefully don't have to do it again. Of course, when you need some updates during the study you can ping me!!! I will show you on Monday.

For RBB there will be only 1 episodes at a time.
